// SPDX-License-Identifier: GPL-3.0
import "./Ownable.sol";
import "./FarmerRole.sol";
import "./DistributorRole.sol";
import "./RetailerRole.sol";
import "./Roles.sol";
import "./Context.sol";

pragma solidity >= 0.5.0 < 0.9.0;

contract main is
    Ownable,
    FarmerRole,
    DistributorRole,
    RetailerRole
{
//   struct Farmer{
//         uint f_id;
//         string f_name;
//         string f_email;
//         uint f_phone;
//         string f_password;
//         string f_location;
//     }

//     struct Distributor{
//         uint d_id;
//         string d_name;
//         string d_email;
//         uint d_phone;
//         string d_password;
//         string d_location;
//     }

//     struct Retailer{
//         uint r_id;
//         string r_name;
//         string r_email;
//         uint r_phone;
//         string r_password;
//         string r_location;
//     }

//     struct Product{
//         uint batch_id;
//         uint productId;
//         string productName;
//         string desc;
//         string productType;
//         string farmer;
//         string distributor;
//         string retailer;
//         string date_of_harvest;
//         address payable distribute;
//         address payable retail;
//     }
    // uint counter = 1;
    // Product[] public products;

    //@Modified Code starts from heree ------->

    address owner;
    // Define a variable called 'productCode' for Universal Product Code (productCode)
    uint256 productCode;
    // Define a variable called 'stockUnit' for Stock Keeping Unit (stockUnit)
    uint256 stockUnit;
    // Define a public mapping 'items' that maps the productCode to an Item.
    mapping(uint256 => Item) items;
    // Define a public mapping 'itemsHistory' that maps the productCode to an array of TxHash,
    // that track its journey through the supply chain -- to be sent from DApp.
    mapping(uint256 => Txblocks) itemsHistory;

    enum Modified {
        CropRegistered,
        ForSaleByFarmer,
        PurchasedByDistributor,
        ShippedByFarmer, // 3
        ReceivedByDistributor, // 4
        ProcessedByDistributor, // 6
        ForSaleByDistributor, // 7
        PurchasedByRetailer, // 8
        ShippedByDistributor, // 9
        ReceivedByRetailer, // 10
        ForSaleByRetailer
    }

    Modified constant defaultState = Modified.CropRegistered;

    struct Item {
        uint256 stockUnit; // Stock Keeping Unit (stockUnit)
        uint256 productCode; // Universal Product Code (productCode), generated by the Farmer, goes on the package, can be verified by the Consumer
        address ownerID; // Metamask-Ethereum address of the current owner as the product moves through 8 stages
        address farmerID; // Metamask-Ethereum address of the Farmer // ADDED PAYABLE
        string farmName; // Farmer Name
        string productDescription; // product Description 
        uint256 productID; // Product ID potentially a combination of productCode + stockUnit
        string productType; // Product types
        string productName;
        uint256 productDate; // Product Date NOTE: MIGHT NEED TO CHANGE type
        uint256 productPrice; // Product Price
        Modified itemState; // Product State as represented in the enum above
        address distributorID; // Metamask-Ethereum address of the Distributor
        address retailerID; // Metamask-Ethereum address of the Retailer
        string distName;
        string retailName;

    }

    // Block number stuct
    struct Txblocks {
        uint256 FTD; // blockfarmerToDistributor
        uint256 DTR; // blockDistributorToRetailer
    }

    event CropRegistered(uint256 productCode); //1
    event ForSaleByFarmer(uint256 productCode); //2
    event PurchasedByDistributor(uint256 productCode); //3
    event ShippedByFarmer(uint256 productCode); //4
    event ReceivedByDistributor(uint256 productCode); //5
    event ProcessedByDistributor(uint256 productCode); //6
    event ForSaleByDistributor(uint256 productCode); //7
    event PurchasedByRetailer(uint256 productCode); //8
    event ShippedByDistributor(uint256 productCode); //9
    event ReceivedByRetailer(uint256 productCode); //10
    event ForSaleByRetailer(uint256 productCode); //11

    // Define a modifer that checks to see if _msgSender() == owner of the contract
    modifier only_Owner() {
        require(_msgSender() == owner);
        _;
    }

    // Define a modifer that verifies the Caller
    modifier verifyCaller(address _address) {
        require(_msgSender() == _address);
        _;
    }

    // Define a modifier that checks if the paid amount is sufficient to cover the price
    modifier paidEnough(uint256 _price) {
        require(msg.value >= _price);
        _;
    }

    // Define a modifier that checks the price and refunds the remaining balance
    modifier checkValue(uint256 _productCode, address payable addressToFund) {
        uint256 _price = items[_productCode].productPrice;
        uint256 amountToReturn = msg.value - _price;
        addressToFund.transfer(amountToReturn);
        _;
    }


    //Item State Modifiers
    modifier producedByFarmer(uint256 _productCode) {
        require(items[_productCode].itemState == Modified.CropRegistered);
        _;
    }

    modifier forSaleByFarmer(uint256 _productCode) {
        require(items[_productCode].itemState == Modified.ForSaleByFarmer);
        _;
    }

    modifier purchasedByDistributor(uint256 _productCode) {
        require(items[_productCode].itemState == Modified.PurchasedByDistributor);
        _;
    }

    modifier shippedByFarmer(uint256 _productCode) {
        require(items[_productCode].itemState == Modified.ShippedByFarmer);
        _;
    }

    modifier receivedByDistributor(uint256 _productCode) {
        require(items[_productCode].itemState == Modified.ReceivedByDistributor);
        _;
    }

      modifier processByDistributor(uint256 _productCode) {
        require(items[_productCode].itemState == Modified.ProcessedByDistributor);
        _;
    }

    modifier forSaleByDistributor(uint256 _productCode) {
        require(items[_productCode].itemState == Modified.ForSaleByDistributor);
        _;
    }

    modifier shippedByDistributor(uint256 _productCode) {
        require(items[_productCode].itemState == Modified.ShippedByDistributor);
        _;
    }

    modifier purchasedByRetailer(uint256 _productCode) {
        require(items[_productCode].itemState == Modified.PurchasedByRetailer);
        _;
    }

    modifier receivedByRetailer(uint256 _productCode) {
        require(items[_productCode].itemState == Modified.ReceivedByRetailer);
        _;
    }

    modifier forSaleByRetailer(uint256 _productCode) {
        require(items[_productCode].itemState == Modified.ForSaleByRetailer);
        _;
    }

    // constructor setup owner stockUnit productCode
    constructor() public payable {
        owner = _msgSender();
        stockUnit = 1;
        productCode = 1;
    }

    // Define a function 'kill'
    function kill() public {
        if (_msgSender() == owner) {
            address payable ownerAddressPayable = _make_payable(owner);
            selfdestruct(ownerAddressPayable);
        }
    }

    // allows you to convert an address into a payable address
    function _make_payable(address x) internal pure returns (address payable) {
        return payable(address(uint160(x)));
    }


/*
 1st step in supplychain
 Allows farmer to create product
*/
    function cropRegisteredByFarmer(
        uint256 _productCode,
        string memory _productName,
        string memory _productType, 
        string memory _productDescription,
        string memory _productDate,
        string memory _farmName,
        uint256 _price
    )
        public onlyFarmer 
    {
        address distributorID; // Empty distributorID address
        address retailerID; // Empty retailerID address
       
        Item memory newProduce; // Create a new struct Item in memory
        newProduce.stockUnit = stockUnit; // Stock Keeping Unit (stockUnit)
        newProduce.productCode = _productCode; // Universal Product Code (productCode), generated by the Farmer, goes on the package, can be verified by the Consumer
        newProduce.ownerID = _msgSender(); // Metamask-Ethereum address of the current owner as the product moves through 8 stages
        newProduce.farmerID = _msgSender(); // Metamask-Ethereum address of the Farmer
        newProduce.farmName = _farmName; // Farmer Name
        newProduce.productDescription = _productDescription; // Product Decription Information
       
        newProduce.productID = _productCode + stockUnit; // Product ID
        newProduce.productType = _productType; // Product Type
        newProduce.productPrice = _price; // Product Price
        newProduce.productDate = block.timestamp;
        
        newProduce.itemState = defaultState; // Product State as represented in the enum above
        newProduce.distributorID = distributorID; // Metamask-Ethereum address of the Distributor
        newProduce.retailerID = retailerID; // Metamask-Ethereum address of the Retailer
       
        items[_productCode] = newProduce; // Add newProduce to items struct by productCode
        uint256 placeholder; // Block number place holder
        Txblocks memory txBlock; // create new txBlock struct
        txBlock.FTD = placeholder; // assign placeholder values
        txBlock.DTR = placeholder;
        
        itemsHistory[_productCode] = txBlock; // add txBlock to itemsHistory mapping by productCode

        // Increment stockUnit
        stockUnit = stockUnit + 1;

        // Emit the appropriate event
        emit CropRegistered(_productCode);
    }

/*
2nd step in supplychain
Allows farmer to sell product
*/
    function sellItemByFarmer(uint256 _productCode, uint256 _price)
        public
        onlyFarmer // check _msgSender() belongs to farmerRole
        producedByFarmer(_productCode) // check items state has been produced
        verifyCaller(items[_productCode].ownerID) // check _msgSender() is owner
    {
        items[_productCode].itemState = Modified.ForSaleByFarmer;
        items[_productCode].productPrice = _price;
        emit ForSaleByFarmer(_productCode);
    }


/*
3rd step in supplychain
Allows distributor to purchase product
*/
    function purchaseItemByDistributor(uint256 _productCode)
        public
        payable
        onlyDistributor // check _msgSender() belongs to distributorRole
        forSaleByFarmer(_productCode) // check items state is for ForSaleByFarmer
        paidEnough(items[_productCode].productPrice) // check if distributor sent enough Ether for product
        checkValue(_productCode, payable(_msgSender())) // check if overpayed return remaing funds back to _msgSender()
    {
        address payable ownerAddressPayable = _make_payable(
            items[_productCode].farmerID
        ); // make originFarmID payable
        ownerAddressPayable.transfer(items[_productCode].productPrice); // transfer funds from distributor to farmer
        items[_productCode].ownerID = _msgSender(); // update owner
        items[_productCode].distributorID = _msgSender(); // update distributor
        items[_productCode].itemState = Modified.PurchasedByDistributor; // update state
        itemsHistory[_productCode].FTD = block.number; // add block number
        emit PurchasedByDistributor(_productCode);
    }

 /*
  4th step in supplychain
  Allows farmer to ship product purchased by distributor
  */
    function shippedItemByFarmer(uint256 _productCode)
        public
        payable
        onlyFarmer // check _msgSender() belongs to FarmerRole
        purchasedByDistributor(_productCode)
        verifyCaller(items[_productCode].farmerID) // check _msgSender() is originFarmID
    {
        items[_productCode].itemState = Modified.ShippedByFarmer; // update state
        emit ShippedByFarmer(_productCode);
    }

    /*
  5th step in supplychain
  Allows distributor to receive product
  */
    function receivedItemByDistributor(uint256 _productCode)
        public
        onlyDistributor // check _msgSender() belongs to DistributorRole
        shippedByFarmer(_productCode)
        verifyCaller(items[_productCode].ownerID) // check _msgSender() is owner
    {
        items[_productCode].itemState = Modified.ReceivedByDistributor; // update state
        emit ReceivedByDistributor(_productCode);
    }

  /*
  6th step in supplychain
  Allows distributor to process product
  */
    function processedItemByDistributor(uint256 _productCode, uint256 slices)
        public
        onlyDistributor // check _msgSender() belongs to DistributorRole
        receivedByDistributor(_productCode)
        verifyCaller(items[_productCode].ownerID) // check _msgSender() is owner
    {
        items[_productCode].itemState = Modified.ProcessedByDistributor; // update state
        
        emit ProcessedByDistributor(_productCode);
    }

/*
  8th step in supplychain
  Allows distributor to sell product
  */
    function sellItemByDistributor(uint256 _productCode, uint256 _price)
        public
        onlyDistributor // check _msgSender() belongs to DistributorRole
        processByDistributor(_productCode)
        verifyCaller(items[_productCode].ownerID) // check _msgSender() is owner
    {
        items[_productCode].itemState = Modified.ForSaleByDistributor;
        items[_productCode].productPrice = _price;
        emit ForSaleByDistributor(_productCode);
    }


    /*
  9th step in supplychain
  Allows retailer to purchase product
  */
    function purchaseItemByRetailer(uint256 _productCode)
        public
        payable
        onlyRetailer // check _msgSender() belongs to RetailerRole
        forSaleByDistributor(_productCode)
        paidEnough(items[_productCode].productPrice)
        checkValue(_productCode, payable(_msgSender()))
    {
        address payable ownerAddressPayable = _make_payable(
            items[_productCode].distributorID
        );
        ownerAddressPayable.transfer(items[_productCode].productPrice);
        items[_productCode].ownerID = _msgSender();
        items[_productCode].retailerID = _msgSender();
        items[_productCode].itemState = Modified.PurchasedByRetailer;
        itemsHistory[_productCode].DTR = block.number;
        emit PurchasedByRetailer(_productCode);
    }


    /*
  10th step in supplychain
  Allows Distributor to
  */
    function shippedItemByDistributor(uint256 _productCode)
        public
        onlyDistributor // check _msgSender() belongs to DistributorRole
        purchasedByRetailer(_productCode)
        verifyCaller(items[_productCode].distributorID) // check _msgSender() is distributorID
    {
        items[_productCode].itemState = Modified.ShippedByDistributor;
        emit ShippedByDistributor(_productCode);
    }

    /*
  11th step in supplychain
  */
    function receivedItemByRetailer(uint256 _productCode)
        public
        onlyRetailer // check _msgSender() belongs to RetailerRole
        shippedByDistributor(_productCode)
        verifyCaller(items[_productCode].ownerID) // check _msgSender() is ownerID
    {
        items[_productCode].itemState = Modified.ReceivedByRetailer;
        emit ReceivedByRetailer(_productCode);
    }

  /*
  12th step in supplychain
  */
    function sellItemByRetailer(uint256 _productCode, uint256 _price)
        public
        onlyRetailer // check _msgSender() belongs to RetailerRole
        receivedByRetailer(_productCode)
        verifyCaller(items[_productCode].ownerID) // check _msgSender() is ownerID
    {
        items[_productCode].itemState = Modified.ForSaleByRetailer;
        items[_productCode].productPrice = _price;
        emit ForSaleByRetailer(_productCode);
    }

    // Define a function 'fetchItemBufferOne' that fetches the data
    function fetchItemBufferOne(uint256 _productCode)
        public
        view
        returns (
            uint256 itemstockUnit,
            uint256 itemproductCode,
            address ownerID,
            address farmerID,
            string memory farmName,
            string memory productDescription,
            uint256 productDate
        )
     {
        // Assign values to the 8 parameters
        Item memory item = items[_productCode];

        return (
            item.stockUnit,
            item.productCode,
            item.ownerID,
            item.farmerID,
            item.farmName,
            item.productDescription,
            item.productDate
        );
    }

    // Define a function 'fetchItemBufferTwo' that fetches the data
    function fetchItemBufferTwo(uint256 _productCode)
        public
        view
        returns (
            uint256 itemstockUnit,
            uint256 itemproductCode,
            uint256 productID,
            string memory productType,
            uint256 productPrice,
            uint256 productDate,
            Modified itemState,
            address distributorID,
            address retailerID
        )
    {
        // Assign values to the 9 parameters
        Item memory item = items[_productCode];

        return (
            item.stockUnit,
            item.productCode,
            item.productID,
            item.productType,
            item.productPrice,
            item.productDate,
            item.itemState,
            item.distributorID,
            item.retailerID
        );
    }


    // Define a function 'fetchItemHistory' that fetaches the data
    function fetchitemHistory(uint256 _productCode)
        public
        view
        returns (
            uint256 blockfarmerToDistributor,
            uint256 blockDistributorToRetailer
        )
    {
        // Assign value to the parameters
        Txblocks memory txblock = itemsHistory[_productCode];
        return (txblock.FTD, txblock.DTR);
    }



    // Farmer public farmer;
    // Distributor public distributor;
    // Retailer public retailer;
    // Product public product;

    // enum State{
    //     allowed,
    //     not_allowed,
    //     wait
    // }

    // State public farmerState = State.allowed;
    // State public DistributorState = State.not_allowed;
    // State public RetailerState = State.not_allowed;

    // string public product_name;
    // string public product_type;
    // string public description;
    // string public dateofharvest;

// ---------------------------------------Farmer Section-----------------------------------//

    // function farmerDetails(
    //     uint _fid, 
    //     string memory _fname, 
    //     string memory _femail,
    //     string memory _flocation, 
    //     uint _fphone, 
    //     string memory _fpass
    //     ) public {
    //         farmer.f_id = _fid;
    //         farmer.f_name = _fname;
    //         farmer.f_email = _femail;
    //         farmer.f_location = _flocation;
    //         farmer.f_phone = _fphone;
    //         farmer.f_password = _fpass;
    // }


    // function cropRegistration(
    //     string memory productname,
    //     string memory producttype, 
    //     string memory descript,
    //     string memory doh
    //     ) public returns(
    //         string memory, 
    //         uint, 
    //         string memory,
    //         string memory, 
    //         string memory,
    //         string memory, 
    //         string memory
    //         ){

    //         string memory farmername = farmer.f_name;
    //         uint farmerphone = farmer.f_phone;   
    //         string memory farmerlocation = farmer.f_location;
            
    //         product_name = productname;
    //         product_type = producttype;
    //         description = descript; 
    //         dateofharvest = doh;
             
    //         return (farmername, farmerphone, dateofharvest, farmerlocation, product_name, product_type, description);        
    // }

    // function addFarmertoProduct() public returns(string memory){
    //     if(farmerState == State.allowed){
    //         product.productName = product_name;
    //         product.productType = product_type;
    //         product.desc = description;
    //         product.farmer = farmer.f_name;
    //         product.date_of_harvest = dateofharvest;
    //         return("Farmer Details are Updated Successfully!!!");
    //     }
    //     else{
    //         revert("Something went wrong in Farmer's state");
    //     }
    // }

    // function soldtoDistrubutor() public returns(string memory){
    //     if(farmerState == State.allowed){
    //         product.distributor = distributor.d_name;
    //         DistributorState = State.allowed;
    //         return("Farmer Sold product to Distributor Successfully!!!!"); 
    //     }
    //     else{
    //         revert("Transaction between farmer and distributor not happened");
    //     }
    // }


//-------------------------------Distributer Section------------------------//

    // function distributorDetails(
    //     uint did,
    //     string memory dname, 
    //     string memory demail, 
    //     string memory dlocation, 
    //     uint dphone, 
    //     string memory dpassword
    //     ) public{
    //         uint d_id = did;
    //         string memory d_name = dname;
    //         string memory d_email = demail;
    //         string memory d_location = dlocation;
    //         uint d_phone = dphone;
    //         string memory d_password = dpassword;

    //         distributor.d_id = d_id;
    //         distributor.d_name = d_name;
    //         distributor.d_email = d_email;
    //         distributor.d_location = d_location;
    //         distributor.d_phone = d_phone;
    //         distributor.d_password = d_password;

    // }

    // function distributorBatch(uint batchId) public returns(string memory){
    //     if(DistributorState == State.allowed && farmerState == State.allowed ){
    //         product.batch_id = batchId;
    //         DistributorState = State.wait;
    //         return("Batch Id is assigned to the product");    
    //     }
    //     else{
    //         revert("Not Assigned Batch ID");
    //     }
    // }

    // function selltoRetailer() public returns(string memory){
    //     if(DistributorState == State.wait && farmerState == State.allowed){
    //         product.retailer = retailer.r_name;
    //         RetailerState = State.allowed;
    //         return("Distributor sold product to retailer");
    //     }
    //     else{
    //         revert("Transaction between distributor and retailer not happened");
    //     }
    // }
    

//---------------------------------------------------retailerDetails--------------------------------------//

    // function retailerDetails(
    //     uint rid, 
    //     string memory rname, 
    //     string memory remail, 
    //     string memory rlocation, 
    //     uint rphone, 
    //     string memory rpassword
    //     ) public{
    //         uint r_id = rid;
    //         string memory r_name = rname;
    //         string memory r_email = remail;
    //         string memory r_location = rlocation;
    //         uint r_phone = rphone;
    //         string memory r_password = rpassword;

    //         retailer.r_id = r_id;
    //         retailer.r_name = r_name;
    //         retailer.r_email = r_email;
    //         retailer.r_location = r_location;
    //         retailer.r_phone = r_phone;
    //         retailer.r_password = r_password;

    // }

//-----------------------------------------------------Product-------------------------------------------------------//

    // function productResult() public view returns(
    //     uint, 
    //     string memory, 
    //     string memory, 
    //     string memory,
    //     string memory, 
    //     string memory, 
    //     string memory, 
    //     string memory
    //     ){  return(
    //         product.batch_id,
    //         product.productName,
    //         product.desc,
    //         product.productType,
    //         product.date_of_harvest,
    //         product.farmer,
    //         product.distributor,
    //         product.retailer
    //     );
    // }

//--------------------------------------------sample-----------------

    // address payable user = payable(0x5B38Da6a701c568545dCfcB03FcB875f56beddC4);
    

}